### ISSUE TITLE
publis to maven central

### ISSUE THREAD

**Issue by piotrturski** [OpenGamma/OG-Commons#81]
plz consider releasing this library so it can be easily used by dependency management tools

**Comment by jodastephen** [comment]
The code that was developed in this repository has been integrated into the more comprehensive [Strata](https://github.com/OpenGamma/Strata) project. the strata-collect and stata-basics modules are the continuation of this code. See also the Strata [website](http://opengamma.github.io/StrataDocs/).

As such, we won't be releasing OG-Commons to maven. But we will release Strata to maven when we reach v1.0.
